### PR TITLE
addFile(): throw an error when the file does not exist

### PR DESCRIPTION
**Pull request by laurence-myers**
Fixes issue #34

### CODE REVIEW

**Comment by kvz** [comment]
Hi @laurence-myers was this closed by accident? 

I guess this PR was open for a long time? I only just got a notification of it, sorry if it slipped through the cracks on our side!

@tim-kos might you know more about this?

**Comment by laurence-myers** [comment]
I was just cleaning out my old open PRs in GitHub. I don't use transloadit,
so don't mind if this gets resolved or not. 🙂

**Comment by kvz** [comment]
> I don't use transloadit

😭  maybe later! 😄 

Sorry to have left this one hanging Laurence. We're usually more punctual with these things :/

**Comment by tim-kos** [comment]
Sorry to not close this sooner. But this was added a long time ago:

```
addFile (name, path) {
    const stream = fs.createReadStream(path)
    stream.on('error', err => {
      // handle the error event to avoid the error being thrown
      console.error(err)
    })
    this.addStream(name, stream)
  }
```

**Pull request closed without merging**
