### PR TITLE
export sdk docs

### PR DESCRIPTION
**Pull request by kvz**

### CODE REVIEW

**Comment by mifi** [comment]
What's the purpose of this? There was already an Examples heading, and now there are two

**Comment by kvz** [comment]
Some automation gone bad, reverted. Readme’s need to follow a fixed format in order for the automation to work, think that broke, will check this out later

**Comment by mifi** [comment]
Oooh ok. is this format documented somewhere?

**Comment by kvz** [comment]
Just in code, you couldn't have known, it's my failure. I have included support for your headings now: https://github.com/transloadit/content/pull/1411/files#diff-9da44f533138cc8b8db045efe04679812c533e3cdff3c7eec3e0235a151b03e7R330-R338

**Pull request merged**
