### PR TITLE
retry getAssembly on 404

### PR DESCRIPTION
**Pull request by mifi**
to workaround server issue

### CODE REVIEW

**Comment by kvz** [comment]
Tim may have found the server issue, maybe this is not needed, let's give it another day?

**Comment by mifi** [comment]
note that we only retry on 404 right after an assembly has been created. An assembly cannot be deleted, right, so it kind of makes sense to retry on 404 as a safeguard

**Comment by Murderlon** [comment]
Adding complexity for a case that should never happen is probably not a safeguard we want. But let's see what Tim comes up with.

**Comment by kvz** [comment]
You can reliably reproduce this right? What about adding that as a test case to the api in a branch? Then we can also prove it has been fixed and will remain that way in the future

**Comment by mifi** [comment]
No I cnanot reproduce, but the customer is seeing it happening sporadically in production. So a unit test won’t help much i think

**Comment by mifi** [comment]
seems to be fixed in api

**Pull request closed without merging**
